### ISSUE TITLE
Elevator does not move

### ISSUE THREAD

**Issue by Jeremy5909** [Pecacheu/Elevators-v2#25]
I can call the elevator up to me, but when I select a floor with the sign, it doesn't move. I am using paper 1.19 with a glass floor.

**Comment by Jeremy5909** [comment]
Fixed, It doesn't work with shield in offhand

**Comment by vmo64** [comment]
I have the same issue, but it still does not move even when i remove shield from offhand
